name: www_music_py36
channels:
- conda-forge
- crowdai
- defaults
dependencies:
- ca-certificates=2018.1.18=0
- certifi=2018.1.18=py36_0
- ncurses=5.9=10
- openssl=1.0.2n=0
- pip=9.0.2=py36_0
- python=3.6.4=0
- readline=7.0=0
- setuptools=39.0.0=py36_0
- sqlite=3.20.1=2
- tk=8.6.7=0
- wheel=0.30.0=py36_2
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - appdirs==1.4.3
  - audioread==2.1.5
  - awscli==1.14.50
  - botocore==1.9.3
  - chardet==3.0.4
  - click==6.7
  - colorama==0.3.7
  - crowdai==1.0.14
  - decorator==4.1.2
  - docker==3.1.1
  - docker-pycreds==0.2.2
  - enum-compat==0.0.2
  - enum34==1.1.6
  - escapism==1.0.0
  - flask==0.12.2
  - idna==2.6
  - ipython-genutils==0.2.0
  - itsdangerous==0.24
  - jinja2==2.9.6
  - jmespath==0.9.3
  - joblib==0.11
  - jupyter-repo2docker==0.5.0
  - librosa==0.5.1
  - llvmlite==0.20.0
  - lxml==4.1.1
  - markupsafe==1.0
  - numba==0.35.0
  - numpy==1.13.3
  - packaging==16.8
  - pandas==0.21.0
  - pyasn1==0.4.2
  - pyparsing==2.2.0
  - python-dateutil==2.6.1
  - python-json-logger==0.1.8
  - pytrends==4.3.0
  - pytz==2017.3
  - requests==2.14.2
  - resampy==0.2.0
  - rsa==3.4.2
  - ruamel.yaml==0.15.35
  - s3transfer==0.1.13
  - scikit-learn==0.19.1
  - scipy==1.0.0
  - six==1.10.0
  - socketio-client-2==0.7.5
  - termcolor==1.1.0
  - tqdm==4.11.2
  - traitlets==4.3.2
  - urllib3==1.22
  - websocket-client==0.40.0
  - werkzeug==0.12.2
